export const ExpVideosData = [
  {
    step: 1,
    url: 'https://youtu.be/hoNb6HuNmU0',
    type: 'PRO',
    title: 'Dwayne Johnson promoting Covid-19 Vaccines',
    description: 'test description kjsaksa sjgfjkas jhsagkjas',
    numberOfViews: 1000,
    experiment: 'ConfirmationBias-T',
  },
  {
    step: 1,
    url: 'https://youtu.be/hoNb6HuNmU0',
    type: 'COUNTER',
    title: 'Dwayne Johnson opposing Covid-19 Vaccines',
    description: 'test description kjsaksa sjgfjkas jhsagkjas',
    numberOfViews: 1000,
    experiment: 'ConfirmationBias-C',
  },
  {
    step: 2,
    url: 'https://youtu.be/hoNb6HuNmU0',
    type: 'Objective',
    title: 'The most liked and shared Indian song in 2020: Ramleela',
    description: 'test description kjsaksa sjgfjkas jhsagkjas',
    numberOfViews: 8000000,
    experiment: 'PopularityBias-T',
  },
  {
    step: 2,
    url: 'https://youtu.be/hoNb6HuNmU0',
    type: 'Objective',
    title: 'Ramleela: catchy title track of the Indian movie released in 2019',
    description: 'test description kjsaksa sjgfjkas jhsagkjas',
    numberOfViews: 2000,
    experiment: 'PopularityBias-C',
  },
  {
    step: 3,
    url: 'https://youtu.be/hoNb6HuNmU0',
    type: 'Negative',
    title: 'Announcer loosing it during the game',
    description: 'test description kjsaksa sjgfjkas jhsagkjas',
    numberOfViews: 2000,
    experiment: 'NegativityBias-T',
  },
  {
    step: 3,
    url: 'https://youtu.be/hoNb6HuNmU0',
    type: 'Objective',
    title: 'Some of the interesting moments during the game',
    description: 'test description kjsaksa sjgfjkas jhsagkjas',
    numberOfViews: 2000,
    experiment: 'NegativityBias-C',
  },
  {
    step: 4,
    url: 'https://youtu.be/hoNb6HuNmU0',
    type: 'Negative',
    title: 'Dwayne Johnson introducing himself',
    description: 'test description kjsaksa sjgfjkas jhsagkjas',
    numberOfViews: 2000,
    experiment: 'CognitiveDissonance-T',
  },
  {
    step: 4,
    url: 'https://youtu.be/hoNb6HuNmU0',
    type: 'Objective',
    title: 'Dwayne Johnson introducing himself',
    description: 'test description kjsaksa sjgfjkas jhsagkjas',
    numberOfViews: 2000,
    experiment: 'CognitiveDissonance-C',
  },
];
