export const ExpVideosData = [
  {
    step: 1,
    url: 'https://vimeo.com/517998199',
    type: 'PRO',
    title: 'Dwayne Johnson promoting Covid-19 Vaccines',
    description: 'test description kjsaksa sjgfjkas jhsagkjas',
    numberOfViews: '1,000',
    experiment: 'ConfirmationBias-T',
  },
  {
    step: 1,
    url: 'https://vimeo.com/517998135',
    type: 'COUNTER',
    title: 'Dwayne Johnson opposing Covid-19 Vaccines',
    description: 'test description kjsaksa sjgfjkas jhsagkjas',
    numberOfViews: '1,000',
    experiment: 'ConfirmationBias-C',
  },
  {
    step: 2,
    url: 'https://vimeo.com/518004500',
    type: 'Popular',
    title: 'The most liked and shared Indian song in 2020: Ramleela',
    description: 'test description kjsaksa sjgfjkas jhsagkjas',
    numberOfViews: '8,000,000',
    experiment: 'PopularityBias-T',
  },
  {
    step: 2,
    url: 'https://vimeo.com/518000225',
    type: 'Non-popular',
    title: 'Ramleela: catchy title track of the Indian movie released in 2019',
    description: 'test description kjsaksa sjgfjkas jhsagkjas',
    numberOfViews: '2,000',
    experiment: 'PopularityBias-C',
  },
  {
    step: 3,
    url: 'https://vimeo.com/517989685',
    type: 'Negative',
    title: 'Announcer losing it during the game',
    description: 'test description kjsaksa sjgfjkas jhsagkjas',
    numberOfViews: '2,000',
    experiment: 'NegativityBias-T',
  },
  {
    step: 3,
    url: 'https://vimeo.com/518724844',
    type: 'Objective',
    title: 'Some of the interesting moments during the game',
    description: 'test description kjsaksa sjgfjkas jhsagkjas',
    numberOfViews: '2,000',
    experiment: 'NegativityBias-C',
  },
  {
    step: 4,
    url: 'https://vimeo.com/517997817',
    type: 'CB',
    title: 'Dwayne Johnson introducing himself',
    description: 'test description kjsaksa sjgfjkas jhsagkjas',
    numberOfViews: '2,000',
    experiment: 'CognitiveDissonance-T',
  },
  {
    step: 4,
    url: 'https://vimeo.com/517997817',
    type: 'CB',
    title: 'Dwayne Johnson introducing himself',
    description: 'test description kjsaksa sjgfjkas jhsagkjas',
    numberOfViews: '2,000',
    experiment: 'CognitiveDissonance-C',
  },
];
